name: pr-assign-author

permissions:
  contents: read

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  run:
    uses: crazy-max/.github/.github/workflows/pr-assign-author.yml@3e5689984859136d8c931e9cbd294412b88baa21
    permissions:
      contents: read
      pull-requests: write
